#!/usr/bin/env python3
"""Generate the Laposta skill's endpoint and schema reference from the API source.

The source of truth is the same structured spec that produces the public API
documentation on docs.laposta.nl: a language neutral structure file plus one
text file per language. This script reads the English text, so the generated
reference matches the published English API reference exactly.

Regenerate whenever the API changes:

    python3 scripts/generate-reference.py

Writes:
    plugins/laposta/skills/laposta/references/endpoints.md
    plugins/laposta/skills/laposta/references/schemas.md
    plugins/laposta/skills/laposta/SKILL.md   (only between the GENERATED:INDEX markers)

Nothing else in SKILL.md is touched, so the hand written guidance stays put.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: pip install pyyaml")

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "spec"
SKILL = ROOT / "plugins" / "laposta" / "skills" / "laposta"
REFS = SKILL / "references"

INDEX_START = "<!-- GENERATED:INDEX:START -->"
INDEX_END = "<!-- GENERATED:INDEX:END -->"

BASE_URL = "https://api.laposta.nl/v2"

# Operations that change or destroy data, or that cost money. The skill must ask
# for explicit confirmation before calling any of these. Derived from the method
# plus an explicit list, because "POST" alone does not separate create from send.
DESTRUCTIVE = {
    "lijstVerwijderen",
    "lijstLeegmaken",
    "veldVerwijderen",
    "segmentVerwijderen",
    "relatieVerwijderen",
    "webhookVerwijderen",
    "campagneVerwijderen",
    "campagneInplannen",
    "campagneVerzenden",
    "lijstSynchroniserenBulk",
}


def load():
    structuur = yaml.safe_load((SPEC / "structuur.yml").read_text(encoding="utf-8"))
    tekst = yaml.safe_load((SPEC / "tekst-en.yml").read_text(encoding="utf-8"))
    extra = yaml.safe_load((SPEC / "schemas-extra.yml").read_text(encoding="utf-8"))
    return structuur, tekst, extra


def clean(text) -> str:
    """Flatten a description to one paragraph of plain text.

    The source text is written for a documentation site: it carries markdown
    links to site paths and the odd newline. A skill reference has no site to
    link into, so site relative links become their own label and absolute links
    are kept.
    """
    if text is None:
        return ""
    text = str(text).strip()
    text = re.sub(r"\[([^\]]+)\]\((/[^)]*)\)", r"\1", text)
    text = re.sub(r"\s*\n\s*", " ", text)
    return re.sub(r"\s{2,}", " ", text).strip()


def typ(param: dict) -> str:
    """Render a parameter type, including its enum when the spec pins one down."""
    t = param.get("type", "string")
    if isinstance(t, list):
        t = "/".join(x for x in t if x != "null")
    if param.get("enum"):
        return f"{t} ({', '.join(str(e) for e in param['enum'])})"
    return str(t)


def param_rows(params, tekst, op_id, want_required: bool):
    rows = []
    for p in params:
        if bool(p.get("verplicht")) is not want_required:
            continue
        desc = clean(tekst.get(f"param.{op_id}.{p['naam']}"))
        groep = p.get("groep") or ""
        naam = f"`{p['naam']}`"
        # The bulk endpoint nests some parameters inside each element of members[].
        if groep == "Member Object":
            naam += " (inside `members[]`)"
        elif groep == "JSON Object":
            naam += " (JSON body)"
        rows.append(f"| {naam} | {p.get('in', '')} | {typ(p)} | {desc} |")
    return rows


def render_endpoints(structuur, tekst) -> str:
    out = [
        "# Laposta API: every endpoint",
        "",
        "Generated by `scripts/generate-reference.py` from the API source. Do not edit by hand.",
        "",
        f"Base URL `{BASE_URL}`. Authentication is HTTP basic with the API key as the",
        "username and an empty password, so in curl that is `-u YOUR_KEY:` including the",
        "colon. Every operation can return `400`, `401` and `429`; see",
        "`errors-and-limits.md` for what those mean and for the numeric error codes,",
        "which are not part of the machine readable spec.",
        "",
    ]

    by_tag: dict[str, list[dict]] = {}
    for ep in structuur["endpoints"]:
        by_tag.setdefault(ep["tag"], []).append(ep)

    for tag in structuur["tags"]:
        naam = tekst.get(f"tag.{tag}.naam", tag.title())
        out.append(f"## {naam}")
        out.append("")
        beschrijving = clean(tekst.get(f"tag.{tag}.beschrijving"))
        if beschrijving:
            out.append(beschrijving)
            out.append("")

        for ep in by_tag.get(tag, []):
            op = ep["id"]
            out.append(f"### {ep['method'].upper()} {ep['pad']}")
            out.append("")
            summary = clean(tekst.get(f"endpoint.{op}.summary"))
            meta = [f"`{op}`", f"returns `{ep['status']}`"]
            if op in DESTRUCTIVE:
                meta.append("**needs confirmation**")
            out.append(f"{summary} ({', '.join(meta)})" if summary else " ".join(meta))
            out.append("")
            description = clean(tekst.get(f"endpoint.{op}.description"))
            if description and description != summary:
                out.append(description)
                out.append("")

            params = ep.get("params") or []
            required = param_rows(params, tekst, op, True)
            optional = param_rows(params, tekst, op, False)
            if required:
                out.append("Required:")
                out.append("")
                out.append("| Parameter | In | Type | Meaning |")
                out.append("| --- | --- | --- | --- |")
                out.extend(required)
                out.append("")
            if optional:
                out.append("Optional:")
                out.append("")
                out.append("| Parameter | In | Type | Meaning |")
                out.append("| --- | --- | --- | --- |")
                out.extend(optional)
                out.append("")
            if not params:
                out.append("Takes no parameters.")
                out.append("")
            out.append(f"Response: `{ep['antwoord']}` (see `schemas.md`).")
            out.append("")

    return "\n".join(out).rstrip() + "\n"


def render_schemas(structuur, tekst, extra) -> str:
    out = [
        "# Laposta API: response objects",
        "",
        "Generated by `scripts/generate-reference.py` from the API source. Do not edit by hand.",
        "",
        "A single object comes back wrapped under its own name, for example",
        "`{\"list\": {...}}`. A collection comes back as `{\"data\": [{\"list\": {...}}, ...]}`",
        "with no pagination: list endpoints always return everything. The two history",
        "endpoints are the exception and use a cursor.",
        "",
    ]

    for naam, schema in structuur["schemas"].items():
        titel = clean(tekst.get(f"schema.{naam}.titel")) or f"The {naam} object"
        out.append(f"## `{naam}`")
        out.append("")
        out.append(titel)
        out.append("")
        out.append("| Field | Type | Meaning |")
        out.append("| --- | --- | --- |")
        for veld in schema["velden"]:
            desc = clean(tekst.get(f"schema.{naam}.{veld['naam']}"))
            t = typ(veld)
            if veld.get("nullable"):
                t += ", may be null or absent"
            out.append(f"| `{veld['naam']}` | {t} | {desc} |")
        out.append("")

    out.append("## Hand written schemas")
    out.append("")
    out.append(
        "These four are not built from the field lists above; they come from the "
        "spec's own schema file. The shape below is the literal definition."
    )
    out.append("")
    for naam, schema in (extra or {}).items():
        out.append(f"### `{naam}`")
        out.append("")
        out.append("```yaml")
        out.append(yaml.safe_dump(schema, allow_unicode=True, sort_keys=False).rstrip())
        out.append("```")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def render_index(structuur, tekst) -> str:
    rows = [
        "| Method | Path | Operation | What it does |",
        "| --- | --- | --- | --- |",
    ]
    for tag in structuur["tags"]:
        for ep in structuur["endpoints"]:
            if ep["tag"] != tag:
                continue
            summary = clean(tekst.get(f"endpoint.{ep['id']}.summary")) or ep["id"]
            mark = " ⚠" if ep["id"] in DESTRUCTIVE else ""
            rows.append(
                f"| {ep['method'].upper()} | `{ep['pad']}` | `{ep['id']}`{mark} | {summary} |"
            )
    return "\n".join(rows)


def patch_skill(index: str, count: int) -> bool:
    path = SKILL / "SKILL.md"
    if not path.exists():
        print(f"! {path} does not exist yet, skipping the index", file=sys.stderr)
        return False
    text = path.read_text(encoding="utf-8")
    if INDEX_START not in text or INDEX_END not in text:
        print("! SKILL.md has no GENERATED:INDEX markers, skipping", file=sys.stderr)
        return False
    block = (
        f"{INDEX_START}\n"
        f"All {count} operations. ⚠ marks the ones that need explicit user confirmation.\n\n"
        f"{index}\n"
        f"{INDEX_END}"
    )
    new = re.sub(
        re.escape(INDEX_START) + r".*?" + re.escape(INDEX_END),
        lambda _: block,
        text,
        flags=re.S,
    )
    if new != text:
        path.write_text(new, encoding="utf-8")
        return True
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated files are out of date instead of writing them",
    )
    args = parser.parse_args()

    structuur, tekst, extra = load()
    REFS.mkdir(parents=True, exist_ok=True)

    wanted = {
        REFS / "endpoints.md": render_endpoints(structuur, tekst),
        REFS / "schemas.md": render_schemas(structuur, tekst, extra),
    }

    stale = []
    for path, content in wanted.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path)
        if not args.check:
            path.write_text(content, encoding="utf-8")

    index = render_index(structuur, tekst)
    if args.check:
        if stale:
            for path in stale:
                print(f"out of date: {path.relative_to(ROOT)}")
            return 1
        print("reference is up to date")
        return 0

    patched = patch_skill(index, len(structuur["endpoints"]))
    print(f"{len(structuur['endpoints'])} operations, {len(structuur['schemas'])} objects")
    for path in wanted:
        print(f"wrote {path.relative_to(ROOT)}")
    if patched:
        print("updated the operation index in SKILL.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
